name: Compilation Check

on:
    push:
        branches: [ master, main ]
    pull_request:
        branches: [ master, main ]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:

        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                toolchain: [stable, beta, nightly]

        steps:
        - uses: actions/checkout@v3
        - name: Set up Rust
          run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
        - name: Build
          run: cargo build --verbose
        - name: Run tests
          run: cargo test --verbose
        - name: Build release
          run: cargo build --verbose --release